# Generated by Django 6.0 on 2026-05-06 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "digikey_part_number",
                    models.CharField(
                        db_index=True,
                        help_text="DigiKey's own part number, e.g. '2648-SC0915TR-ND'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "manufacturer_pn",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Manufacturer's part number, e.g. 'ATmega328P-PU'",
                        max_length=100,
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(blank=True, db_index=True, max_length=150),
                ),
                ("product_url", models.URLField(blank=True, max_length=500)),
                ("datasheet_url", models.URLField(blank=True, max_length=500)),
                (
                    "sync_source",
                    models.CharField(
                        choices=[("digikey", "DigiKey"), ("mouser", "Mouser")],
                        default="digikey",
                        max_length=20,
                    ),
                ),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Set False when a part goes EOL or is delisted.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["manufacturer", "manufacturer_pn"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="maker_parts_categor_68c1b5_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ComponentPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "distributor",
                    models.CharField(
                        choices=[("digikey", "DigiKey"), ("mouser", "Mouser")],
                        default="digikey",
                        max_length=20,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Single-unit price in USD.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "stock_qty",
                    models.IntegerField(
                        default=0, help_text="Units available at time of sync."
                    ),
                ),
                ("pricing_tiers", models.JSONField(blank=True, default=list)),
                ("fetched_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="maker_parts.component",
                    ),
                ),
            ],
            options={
                "ordering": ["-fetched_at"],
                "indexes": [
                    models.Index(
                        fields=["component", "-fetched_at"],
                        name="maker_parts_compone_92abb0_idx",
                    )
                ],
            },
        ),
    ]
