# Generated by Django 6.0 on 2026-05-06 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maker_parts", "0001_initial"),
        ("maker_projects", "0012_delete_checkpoint"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        help_text="e.g. '10k variant' or 'any 5V regulator works'",
                        max_length=255,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_uses",
                        to="maker_parts.component",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="maker_projects.makerproject",
                    ),
                ),
            ],
            options={
                "ordering": ["added_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "component"), name="unique_part_per_project"
                    )
                ],
            },
        ),
    ]
