# Generated by Django 6.0 on 2025-12-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email",
            field=models.TextField(blank=True),
        ),
    ]
