# Generated by Django 6.0 on 2026-05-05 03:34

from django.db import migrations

def update_site(apps, schema_editor):
    try:
        SiteModel = apps.get_model("sites", "Site")
        SiteModel.objects.filter(id=1).update(
            domain="makerbuddy.cjvillarreal.com",
            name="makerbuddy.cjvillarreal.com"
        )
    except LookupError:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_userprofile_email"),
    ]

    operations = [
        migrations.RunPython(update_site, migrations.RunPython.noop),
    ]
