# Generated by Django 6.0 on 2025-12-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maker_projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="makerproject",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("completed", "Completed")],
                default="active",
                max_length=20,
            ),
        ),
    ]
