# Generated by Django 6.0 on 2025-12-16 23:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maker_projects", "0002_alter_project_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Project",
            new_name="MakerProjects",
        ),
    ]
