# Generated by Django 6.0 on 2025-12-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maker_projects", "0002_alter_makerproject_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="makerproject",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
