# Generated by Django 6.0 on 2025-12-17 00:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maker_projects", "0003_rename_project_makerprojects"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MakerProjects",
            new_name="MakerProject",
        ),
    ]
