# Generated by Django 6.0 on 2026-01-28 19:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maker_projects", "0004_projectlike"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("gitlab", "GitLab"),
                            ("bitbucket", "Bitbucket"),
                            ("docs", "Documentation"),
                            ("video", "Demo Video"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        max_length=500,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="maker_projects.makerproject",
                    ),
                ),
            ],
        ),
    ]
