# Generated by Django 6.0 on 2025-12-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maker_projects", "0004_rename_makerprojects_makerproject"),
    ]

    operations = [
        migrations.AddField(
            model_name="makerproject",
            name="code_snippet",
            field=models.TextField(blank=True),
        ),
    ]
