# Generated by Django 6.0 on 2026-01-28 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maker_projects", "0005_projectlink"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="makerproject",
            name="code_snippet",
        ),
    ]
