# Generated by Django 6.0 on 2025-12-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maker_projects", "0005_makerproject_code_snippet"),
    ]

    operations = [
        migrations.AddField(
            model_name="makerproject",
            name="image",
            field=models.ImageField(blank=True, upload_to="project_images/"),
        ),
    ]
