# Generated by Django 6.0 on 2026-01-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maker_projects", "0006_remove_makerproject_code_snippet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectlink",
            name="link_type",
            field=models.CharField(
                choices=[
                    ("github", "GitHub"),
                    ("gitlab", "GitLab"),
                    ("bitbucket", "Bitbucket"),
                    ("docs", "Documentation"),
                    ("video", "Demo Video"),
                ],
                editable=False,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="projectlink",
            name="url",
            field=models.URLField(max_length=500),
        ),
    ]
