# Generated by Django 6.0 on 2025-12-17 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maker_projects", "0007_checkpoint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkpoint",
            name="owner",
        ),
        migrations.AddField(
            model_name="checkpoint",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkpoints",
                to="maker_projects.makerproject",
            ),
            preserve_default=False,
        ),
    ]
