# Generated by Django 6.0 on 2026-01-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maker_projects", "0007_alter_projectlink_link_type_alter_projectlink_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectlink",
            name="link_type",
            field=models.CharField(
                choices=[
                    ("github", "GitHub"),
                    ("gitlab", "GitLab"),
                    ("bitbucket", "Bitbucket"),
                    ("video", "Demo Video"),
                ],
                editable=False,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="projectlink",
            name="url",
            field=models.URLField(help_text="gitHub,BitBucket,YouTube", max_length=500),
        ),
    ]
