# Generated by Django 6.0 on 2026-01-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maker_projects", "0008_alter_projectlink_link_type_alter_projectlink_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectlink",
            name="url",
            field=models.URLField(max_length=500),
        ),
    ]
