# Generated by Django 6.0 on 2026-01-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maker_projects", "0009_alter_projectlink_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="makerproject",
            name="definition_of_done",
            field=models.TextField(
                blank=True,
                help_text="Clear description of when this project is considered complete",
            ),
        ),
        migrations.AddField(
            model_name="makerproject",
            name="goal",
            field=models.CharField(
                blank=True,
                help_text="Short, single-sentence goal for the project",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="makerproject",
            name="due_date",
            field=models.DateField(
                blank=True,
                help_text="Set reasonable timeframe to finish your project.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="makerproject",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Please add an image of your hardware.",
                upload_to="project_images/",
            ),
        ),
        migrations.AlterField(
            model_name="makerproject",
            name="title",
            field=models.CharField(
                help_text="Give your project a descriptive name.", max_length=200
            ),
        ),
    ]
