# Generated by Django 6.0 on 2026-02-28 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maker_projects", "0011_projectfeature_projectrequirement"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CheckPoint",
        ),
    ]
