# Generated by Django 6.0 on 2026-05-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maker_projects", "0013_buildstep_delete_projectfeature"),
    ]

    operations = [
        migrations.AddField(
            model_name="makerproject",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=False),
        ),
    ]
