# Generated by Django 6.0 on 2026-05-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maker_projects", "0014_makerproject_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="makerproject",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
